# Generated by Django 5.0.12 on 2025-06-08 11:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HighLight',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=2555)),
            ],
            options={
                'verbose_name_plural': 'Highlights',
            },
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='packages/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('days', models.IntegerField(default=0)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('pdf_url', models.URLField(blank=True)),
                ('video', models.URLField(blank=True)),
                ('highlights', models.ManyToManyField(blank=True, to='packages.highlight')),
            ],
            options={
                'verbose_name_plural': 'Packages',
            },
        ),
    ]
