# Generated by Django 5.0.12 on 2025-06-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='pdf_url',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='video',
        ),
        migrations.AddField(
            model_name='packages',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='packages/pdfs/'),
        ),
        migrations.AddField(
            model_name='packages',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='packages/videos/'),
        ),
    ]
