# Generated by Django 5.0.12 on 2025-06-08 14:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_remove_packages_pdf_url_remove_packages_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegePartners',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='college/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('highlights', models.CharField(max_length=255)),
                ('col_num', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'College-Partners',
            },
        ),
    ]
