# Generated by Django 5.0.12 on 2025-06-09 06:52

import ckeditor.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_trip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='author/')),
                ('name', models.CharField(max_length=255)),
                ('sub_heading', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Blog-Tags',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('highlight', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='blog/')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('sub_heading', models.CharField(max_length=255)),
                ('min_read', models.IntegerField()),
                ('is_published', models.BooleanField(default=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.author')),
                ('related_blogs', models.ManyToManyField(blank=True, to='packages.blog')),
                ('blog_tags', models.ManyToManyField(to='packages.blogtag')),
            ],
            options={
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
