# Generated by Django 5.0.12 on 2025-06-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_author_blogtag_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='sub_heading',
            field=models.TextField(),
        ),
    ]
