# Generated by Django 5.0.12 on 2025-06-09 08:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_alter_blog_sub_heading'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailHere',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=2555)),
            ],
            options={
                'verbose_name_plural': 'Blog-Tags',
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
