# Generated by Django 5.0.12 on 2025-06-11 14:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0010_alter_emailhere_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryVideo',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('video', models.FileField(upload_to='memory_videos/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Memory-Videos',
            },
        ),
        migrations.AlterModelOptions(
            name='emailhere',
            options={'verbose_name_plural': 'User-Emails'},
        ),
    ]
